server:
  port: 8091

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: http://localhost:7777/
        predicates:
          - Path=/student/**

#    -id: courseModule
#    uri: http://localhost:7778/
#    predicates:
#      -Path =/course/**
#    filters:
#      -name: RequestSize
#      args:
#        Maxsize: 50000
