spring:
  application:
    name: student-service

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    properties:
      hibernates: #this could be wrong here
        dialect: ${datasource.dialect}
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true

      show-sql: true
      hibernate:
        ddl-auto: none

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8083/eureka
